import React from "react";
import { Avatar, Card, Col, Menu, Row, Statistic, Table, Tag } from "antd";
import { AppstoreOutlined, DollarOutlined, InboxOutlined, ShoppingCartOutlined, TeamOutlined, UserOutlined } from "@ant-design/icons";

const orders = [{ key: "1", id: "#NS1001", customer: "Nguyễn Minh Anh", total: "1.290.000 ₫", status: "Đang giao" }, { key: "2", id: "#NS1002", customer: "Trần Gia Hân", total: "850.000 ₫", status: "Hoàn tất" }, { key: "3", id: "#NS1003", customer: "Lê Quốc Bảo", total: "2.490.000 ₫", status: "Chờ xác nhận" }];
const columns = [{ title: "Mã đơn", dataIndex: "id" }, { title: "Khách hàng", dataIndex: "customer" }, { title: "Tổng tiền", dataIndex: "total" }, { title: "Trạng thái", dataIndex: "status", render: (status) => <Tag color={status === "Hoàn tất" ? "green" : status === "Đang giao" ? "blue" : "orange"}>{status}</Tag> }];
const statCards = [["Doanh thu tháng", "24.500.000 ₫", <DollarOutlined />, "#1677ff"], ["Đơn hàng mới", "128", <ShoppingCartOutlined />, "#fa8c16"], ["Sản phẩm đang bán", "356", <InboxOutlined />, "#52c41a"], ["Khách hàng", "1.284", <TeamOutlined />, "#722ed1"]];

const AdminPage = () => <div style={{ minHeight: "100vh", background: "#f5f7fb", display: "flex" }}><aside style={{ width: 250, background: "#102a43", color: "#fff", padding: "22px 12px" }}><div style={{ fontSize: 22, fontWeight: 800, padding: "0 14px 24px" }}>NovaShop Admin</div><Menu theme="dark" mode="inline" defaultSelectedKeys={["dashboard"]} style={{ background: "transparent" }} items={[{ key: "dashboard", icon: <AppstoreOutlined />, label: "Tổng quan" }, { key: "products", icon: <InboxOutlined />, label: "Sản phẩm" }, { key: "orders", icon: <ShoppingCartOutlined />, label: "Đơn hàng" }, { key: "users", icon: <TeamOutlined />, label: "Khách hàng" }]} /></aside><main style={{ flex: 1, padding: "26px 32px" }}><header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 26 }}><div><h1 style={{ margin: 0, fontSize: 26 }}>Tổng quan</h1><span style={{ color: "#697586" }}>Cập nhật hoạt động cửa hàng hôm nay</span></div><div style={{ display: "flex", alignItems: "center", gap: 10 }}><Avatar icon={<UserOutlined />} /><b>Quản trị viên</b></div></header><Row gutter={[18, 18]}>{statCards.map(([title, value, icon, color]) => <Col xs={24} sm={12} xl={6} key={title}><Card bordered={false}><div style={{ display: "flex", alignItems: "center", gap: 16 }}><div style={{ width: 46, height: 46, borderRadius: 12, color, background: `${color}18`, display: "grid", placeItems: "center", fontSize: 23 }}>{icon}</div><Statistic title={title} value={value} /></div></Card></Col>)}</Row><Row gutter={[18, 18]} style={{ marginTop: 8 }}><Col xs={24} xl={15}><Card title="Doanh thu 7 ngày qua" bordered={false}><div style={{ height: 210, display: "flex", alignItems: "end", gap: 15, padding: "10px 12px" }}>{[45, 70, 52, 85, 62, 94, 76].map((height, index) => <div key={index} style={{ flex: 1, textAlign: "center" }}><div style={{ height: `${height}%`, minHeight: 20, borderRadius: "8px 8px 2px 2px", background: "linear-gradient(#5b9cff, #1677ff)" }} /><small>T{index + 2}</small></div>)}</div></Card></Col><Col xs={24} xl={9}><Card title="Tình trạng đơn hàng" bordered={false}><p><Tag color="orange">18</Tag> Chờ xác nhận</p><p><Tag color="blue">42</Tag> Đang giao</p><p><Tag color="green">68</Tag> Hoàn tất</p><p><Tag color="red">3</Tag> Đã hủy</p></Card></Col></Row><Card title="Đơn hàng gần đây" bordered={false} style={{ marginTop: 18 }}><Table columns={columns} dataSource={orders} pagination={false} /></Card></main></div>;

export default AdminPage;
